### ISSUE TITLE
Add jp2k please

### ISSUE THREAD

**Issue by fdncred** [mazoea/te-external#1]
I love your build system here. It makes building leptonica effortless. I do have a request though. Recently Dan @ leptonica added functionality for jpeg2000. Of course, without the dependency here I cannot use that new functionality. Would you please consider adding it?

Thanks,
Darren

**Comment by vidiecan** [comment]
@fdncred thanks for the comment. adding jpeg2000 is not our priority but you can create a PR and we will add it.
